# LLM API 配置文件
# 请根据实际情况填写API密钥和配置参数

# OpenAI 配置
openai:
  api_key: "${OPENAI_API_KEY}"  # 从环境变量获取
  model: "gpt-4o"        # 可选: gpt-4, gpt-3.5-turbo-16k
  temperature: 0.1              # 较低的温度确保分类一致性
  max_tokens: 8000               # 最大回复长度
  timeout: 60                   # 请求超时时间(秒)
  max_retries: 3                # 失败重试次数
  
# Claude 配置 (可选)
claude:
  api_key: "${CLAUDE_API_KEY}"
  model: "claude-3-sonnet-20240229"
  max_tokens: 800
  temperature: 0.1
  timeout: 30
  max_retries: 3

# 通义千问配置 (可选)
qwen:
  api_key: "${QWEN_API_KEY}"
  model: "qwen-turbo"
  temperature: 0.1
  max_tokens: 800
  timeout: 30

# 智谱AI配置 (可选)  
zhipu:
  api_key: "${ZHIPU_API_KEY}"
  model: "glm-4"
  temperature: 0.1
  max_tokens: 800
  timeout: 30

# 默认使用的分类器
default_classifier: "openai"

# 分类器优先级 (按顺序尝试)
classifier_priority:
  - "openai"
  - "claude" 
  - "qwen"

# 批处理配置
batch_processing:
  batch_size: 5                 # 每批处理论文数量
  delay_between_batches: 1      # 批次间延迟(秒)
  delay_between_requests: 0.5   # 请求间延迟(秒)

# 错误处理配置
error_handling:
  max_classification_retries: 3  # 单个论文最大重试次数
  fallback_to_keyword: true      # 是否回退到关键词分类
  save_failed_papers: true       # 是否保存分类失败的论文

# 质量控制
quality_control:
  min_confidence_threshold: 0.3  # 最低置信度阈值
  require_manual_review: false   # 是否需要人工审核
  manual_review_threshold: 0.6   # 需要人工审核的置信度阈值